version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    groups:
      all-npm:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      all-github-actions:
        patterns:
          - "*"

  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: monthly
    groups:
      all-devcontainers:
        patterns:
          - "*"