# test build site
name: Build

on:
  pull_request:
    branches: ["master"]
  
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: lts/Iron
          cache: npm
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build
