name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build site
        run: hugo

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public

      - name: Load site
        run: curl https://mwrona.com --location --output /dev/null

      - name: Update sitemap
        run: curl http://www.google.com/ping?sitemap=https://mwrona.com/sitemap.xml
